services:
  # mongo:
  #   image: mongo:7
  #   container_name: flash-mongo
  #   ports:
  #     - "27017:27017"
  #   command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
  #   volumes:
  #     - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: flash-redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--notify-keyspace-events", "Ex"]

volumes:
  mongo-data:
